### ISSUE TITLE
Need an ExecuteMany method

### ISSUE THREAD

**Issue by DavidJacobson** [palantir/sqlite3worker#1]
The regular sqlite3 library has an execute many method, that would be really useful. This is just a request

**Comment by dashawn888** [comment]
Hey,

This seems possible. I'll take a look at adding this when I get time. If you would like feel free to send me a pull request.

Thanks,

Shawn

Sent from Windows Mail

**Comment by DavidJacobson** [comment]
#2 I created it here, it might need some work though. Once it's good to go I'll close this
