### ISSUE TITLE
Confusing shebang lines in non-executable files.

### ISSUE THREAD

**Issue by rjw57** [palantir/sqlite3worker#5]
setup.py, sqlite3worker.py and sqlite3worker_test.py all have the following shebang line:

```
#!/usr/bin/env python
```

but none are actually marked as executable. It makes sense for setup.py to be executable and, perhaps, sqlite3worker_test.py but irrespective of which files should have a shebang line, I'd expect those that _do_ to actually be executable :).

I'd open a pull-request but it's essentially a personal taste issue as to which files are intended to be directly executed and my opinion is no better than anyone else's here!

**Comment by rjw57** [comment]
(This is undoubtedly a minor issue. It's a trivial fix, though; the maintainer just needs to make the call.)

**Comment by dashawn888** [comment]
https://github.com/palantir/sqlite3worker/commit/01b5e0f659b458878d8113b9abbda568e77eaab3 Fixes this. Thanks for pointing this out.
